
#ifndef __CAP_SENSOR_H_
#define __CAP_SENSOR_H_

#include "NUC400Series.h"

int InitOV7725_VGA_YUV422(void);
#define OV7725SensorPolarity         (CAP_CAPPAR_VSP_HIGH | CAP_CAPPAR_HSP_LOW  | CAP_CAPPAR_PCLKP_HIGH)
#define OV7725DataFormatAndOrder (CAP_CAPPAR_PDORD_UYVY | CAP_CAPPAR_INFMT_YUV422 | CAP_CAPPAR_OUTFMT_YUV422)

int InitNT99141_VGA_YUV422(void);
#define NT99141SensorPolarity         (CAP_CAPPAR_VSP_LOW | CAP_CAPPAR_HSP_LOW  | CAP_CAPPAR_PCLKP_HIGH)
#define NT99141DataFormatAndOrder (CAP_CAPPAR_PDORD_YUYV | CAP_CAPPAR_INFMT_YUV422 | CAP_CAPPAR_OUTFMT_YUV422)

#endif
