/**
 *******************************************************************************
 * @file    TB0_LED.c
 * @brief   The application functions of TB0_LED demo for the TOSHIBA
 *          'TMPM362' Device Series
 * @version V0.100
 * @date    2010/6/21
 * 
 * THE SOURCE CODE AND ITS RELATED DOCUMENTATION IS PROVIDED "AS IS". TOSHIBA
 * CORPORATION MAKES NO OTHER WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED OR,
 * STATUTORY AND DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
 * SATISFACTORY QUALITY, NON INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
 *
 * THE SOURCE CODE AND DOCUMENTATION MAY INCLUDE ERRORS. TOSHIBA CORPORATION
 * RESERVES THE RIGHT TO INCORPORATE MODIFICATIONS TO THE SOURCE CODE IN LATER
 * REVISIONS OF IT, AND TO MAKE IMPROVEMENTS OR CHANGES IN THE DOCUMENTATION OR
 * THE PRODUCTS OR TECHNOLOGIES DESCRIBED THEREIN AT ANY TIME.
 *
 * TOSHIBA CORPORATION SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT OR
 * CONSEQUENTIAL DAMAGE OR LIABILITY ARISING FROM YOUR USE OF THE SOURCE CODE OR
 * ANY DOCUMENTATION, INCLUDING BUT NOT LIMITED TO, LOST REVENUES, DATA OR
 * PROFITS, DAMAGES OF ANY SPECIAL, INCIDENTAL OR CONSEQUENTIAL NATURE, PUNITIVE
 * DAMAGES, LOSS OF PROPERTY OR LOSS OF PROFITS ARISING OUT OF OR IN CONNECTION
 * WITH THIS AGREEMENT, OR BEING UNUSABLE, EVEN IF ADVISED OF THE POSSIBILITY OR
 * PROBABILITY OF SUCH DAMAGES AND WHETHER A CLAIM FOR SUCH DAMAGE IS BASED UPON
 * WARRANTY, CONTRACT, TORT, NEGLIGENCE OR OTHERWISE.
 *
 * (C)Copyright TOSHIBA CORPORATION 2010 All rights reserved
 *******************************************************************************
 */

#include "tmpm362_tmrb.h"
#define TMRB_PERIOD 0x1F40U

TMRB_InitTypeDef myTMRB;

void INTTB0_IRQHandler(void);

void TB0_LED(void)
{
    TSB_PM_DATA_PM4 = 1;
    TSB_PM_CR_PM4C = 1;

    myTMRB.Mode = TMRB_INTERVAL_TIMER;
    myTMRB.ClkDiv = TMRB_CLK_DIV_8;
    myTMRB.Cycle = TMRB_PERIOD;        /* Specific value depends on system clock */
    myTMRB.UpCntCtrl = TMRB_AUTO_CLEAR;
    myTMRB.Duty = TMRB_PERIOD / 2U;     /* Specific value depends on system clock */
       
    TMRB_Enable(TSB_TB0);
    TMRB_Init(TSB_TB0, &myTMRB);
    TMRB_SetRunState(TSB_TB0, TMRB_RUN);
    NVIC_EnableIRQ(INTTB0_IRQn);
    while (1) {
        /* Do nothing */
    }
}

void INTTB0_IRQHandler(void)
{
    static uint32_t cnt = 0U;
    
    cnt++;
    if (cnt < 1000U) {
        TSB_PM_DATA_PM4 = 0;
    } else if (cnt < 2000U) {
        TSB_PM_DATA_PM4 = 1;
    } else {
        cnt = 0U;
        TSB_PM_DATA_PM4 = 0;
    }
}
